package multivers

type Customer struct {
	AccountManagerID                    string        `json:"accountManagerId,omitempty"`
	Addresses                           interface{}   `json:"addresses,omitempty"`
	Messages                            []interface{} `json:"messages,omitempty"`
	ApplyOrderSurcharge                 bool          `json:"applyOrderSurcharge,omitempty"`
	BusinessNumber                      string        `json:"businessNumber,omitempty"`
	CanChange                           bool          `json:"canChange,omitempty"`
	CannotChangeReason                  string        `json:"cannotChangeReason,omitempty"`
	ChargeVatTypeID                     int           `json:"chargeVatTypeId,omitempty"`
	City                                string        `json:"city,omitempty"`
	CocCity                             string        `json:"cocCity,omitempty"`
	CocDate                             string        `json:"cocDate,omitempty"`
	CocRegistration                     string        `json:"cocRegistration,omitempty"`
	CollectiveInvoiceSystemID           string        `json:"collectiveInvoiceSystemId,omitempty"`
	CombineInvoicesForElectronicBanking bool          `json:"combineInvoicesForElectronicBanking,omitempty"`
	CountryID                           string        `json:"countryId,omitempty"`
	CreditLimit                         float64       `json:"creditLimit,omitempty"`
	CreditSqueezeID                     string        `json:"creditSqueezeId,omitempty"`
	CurrencyID                          string        `json:"currencyId,omitempty"`
	CustomerGroupID                     int           `json:"customerGroupId,omitempty"`
	CustomerID                          string        `json:"customerId,omitempty"`
	CustomerStateID                     string        `json:"customerStateId,omitempty"`
	Database                            string        `json:"database,omitempty"`
	DateChanged                         string        `json:"dateChanged,omitempty"`
	DateCreated                         string        `json:"dateCreated,omitempty"`
	DeliveryConditionID                 string        `json:"deliveryConditionId,omitempty"`
	DiscountPercentage                  float64       `json:"discountPercentage,omitempty"`
	Email                               string        `json:"email,omitempty"`
	Fax                                 string        `json:"fax,omitempty"`
	FullAddress                         string        `json:"fullAddress,omitempty"`
	FullDeliveryAddress                 string        `json:"fullDeliveryAddress,omitempty"`
	GoogleMapsDirectionsURL             string        `json:"googleMapsDirectionsUrl,omitempty"`
	GoogleMapsURL                       string        `json:"googleMapsUrl,omitempty"`
	GovernmentDigitalID                 string        `json:"governmentDigitalId,omitempty"`
	HasOutstandingBalance               bool          `json:"hasOutstandingBalance,omitempty"`
	Homepage                            string        `json:"homepage,omitempty"`
	IncludeVatOnOrderByDefault          bool          `json:"includeVatOnOrderByDefault,omitempty"`
	IntrastatGoodsCodeID                int           `json:"intrastatGoodsCodeId,omitempty"`
	IntrastatGoodsDistributionID        int           `json:"intrastatGoodsDistributionId,omitempty"`
	IntrastatStatSystemID               int           `json:"intrastatStatSystemId,omitempty"`
	IntrastatTrafficRegionID            int           `json:"intrastatTrafficRegionId,omitempty"`
	IntrastatTransactionTypeID          string        `json:"intrastatTransactionTypeId,omitempty"`
	IntrastatTransportTypeID            int           `json:"intrastatTransportTypeId,omitempty"`
	InvoiceOnBehalfOfMembers            bool          `json:"invoiceOnBehalfOfMembers,omitempty"`
	IsDunForPayment                     bool          `json:"isDunForPayment,omitempty"`
	IsInFactoring                       bool          `json:"isInFactoring,omitempty"`
	IsPaymentRefRequired                bool          `json:"isPaymentRefRequired,omitempty"`
	IsPurchaseOrganization              bool          `json:"isPurchaseOrganization,omitempty"`
	LanguageID                          string        `json:"languageId,omitempty"`
	MobilePhone                         string        `json:"mobilePhone,omitempty"`
	Name                                string        `json:"name"`
	OrganizationID                      int           `json:"organizationId,omitempty"`
	PaymentConditionID                  string        `json:"paymentConditionId,omitempty"`
	Person                              string        `json:"person,omitempty"`
	PricelistID                         string        `json:"pricelistId,omitempty"`
	PrintPurchaseDetails                bool          `json:"printPurchaseDetails,omitempty"`
	PurchaseOrganizationID              string        `json:"purchaseOrganizationId,omitempty"`
	PurchaseOrganizationMemberID        string        `json:"purchaseOrganizationMemberId,omitempty"`
	RevenueAccountID                    string        `json:"revenueAccountId,omitempty"`
	ShortName                           string        `json:"shortName"`
	Street1                             string        `json:"street1,omitempty"`
	Street2                             string        `json:"street2,omitempty"`
	SupplierID                          string        `json:"supplierId,omitempty"`
	Telephone                           string        `json:"telephone,omitempty"`
	UsesUBLInvoice                      bool          `json:"usesUBLInvoice,omitempty"`
	VatNumber                           string        `json:"vatNumber,omitempty"`
	VatScenarioID                       int           `json:"vatScenarioId,omitempty"`
	VatVerificationDate                 string        `json:"vatVerificationDate,omitempty"`
	ZipCode                             string        `json:"zipCode,omitempty"`
}
