package multivers

type CustomerInvoice struct {
	AccountManager         string               `json:"accountManager,omitempty"`
	AccountManagerID       string               `json:"accountManagerId,omitempty"`
	Messages               []interface{}        `json:"messages,omitempty"`
	AmountCreditSqueeze    float64              `json:"amountCreditSqueeze,omitempty"`
	AmountCreditSqueezeCur float64              `json:"amountCreditSqueezeCur,omitempty"`
	AmountRebate           float64              `json:"amountRebate"`
	AmountRebateCur        float64              `json:"amountRebateCur"`
	AmountTotal            float64              `json:"amountTotal"`
	AmountTotalCur         float64              `json:"amountTotalCur"`
	AutoCalculateVat       bool                 `json:"autoCalculateVat"`
	BordereauxNumber       string               `json:"bordereauxNumber"`
	CanChange              bool                 `json:"canChange"`
	CannotChangeReason     string               `json:"cannotChangeReason"`
	ContactPerson          string               `json:"contactPerson"`
	ContactPersonID        string               `json:"contactPersonId"`
	CurrencyID             string               `json:"currencyId,omitempty"`
	CustomerID             string               `json:"customerId"`
	CustomerInvoiceLines   CustomerInvoiceLines `json:"customerInvoiceLines"`
	DocumentLink           *struct {
		Messages           []interface{} `json:"messages"`
		CanChange          bool          `json:"canChange"`
		CannotChangeReason string        `json:"cannotChangeReason"`
		DateCreated        string        `json:"dateCreated"`
		Description        string        `json:"description"`
		DocumentLink       string        `json:"documentLink"`
		DocumentType       string        `json:"documentType"`
		LinkCategoryName   string        `json:"linkCategoryName"`
		LinkID             string        `json:"linkId"`
		LinkType           string        `json:"linkType"`
		Reference          string        `json:"reference"`
		Subject            string        `json:"subject"`
	} `json:"documentLink,omitempty"`
	DocumentNumber        int         `json:"documentNumber,omitempty"`
	DunForPayment         bool        `json:"dunForPayment,omitempty"`
	ExchangeRate          float64     `json:"exchangeRate,omitempty"`
	FiscalYear            int         `json:"fiscalYear"`
	InDirectDebitBatch    bool        `json:"inDirectDebitBatch,omitempty"`
	InvoiceDate           string      `json:"invoiceDate"`
	InvoiceExpirationDate string      `json:"invoiceExpirationDate"`
	InvoiceID             string      `json:"invoiceId,omitempty"`
	InvoiceType           int         `json:"invoiceType"`
	JournalID             string      `json:"journalId"`
	JournalSection        string      `json:"journalSection,omitempty"`
	JournalTransaction    int         `json:"journalTransaction,omitempty"`
	KvcPaymentCondition   bool        `json:"kvcPaymentCondition,omitempty"`
	MandateID             string      `json:"mandateId,omitempty"`
	NumberOfReminders     int         `json:"numberOfReminders"`
	OpeningBalance        bool        `json:"openingBalance"`
	OrderID               string      `json:"orderId"`
	PaymentConditionID    string      `json:"paymentConditionId,omitempty"`
	PaymentID             string      `json:"paymentId,omitempty"`
	PaymentReference      string      `json:"paymentReference"`
	PeriodNumber          int         `json:"periodNumber"`
	ProcessedBy           string      `json:"processedBy"`
	ProcessedByID         string      `json:"processedById"`
	RebateExpirationDate  string      `json:"rebateExpirationDate"`
	RebatePercentage      float64     `json:"rebatePercentage"`
	Reference             string      `json:"reference"`
	SystemInvoice         bool        `json:"systemInvoice"`
	TotalAmountVatExcl    float64     `json:"totalAmountVatExcl"`
	TotalAmountVatExclCur float64     `json:"totalAmountVatExclCur"`
	VatAdjusted           bool        `json:"vatAdjusted"`
	VatAmount             float64     `json:"vatAmount"`
	VatAmountCur          float64     `json:"vatAmountCur"`
	VatOnInvoice          bool        `json:"vatOnInvoice"`
	VatScenarioID         int         `json:"vatScenarioId,omitempty"`
	VatTransactionLines   interface{} `json:"vatTransactionLines"`
}

type CustomerInvoiceLines []CustomerInvoiceLine

type CustomerInvoiceLine struct {
	AccountID                 string      `json:"accountId"`
	CostCentreID              string      `json:"costCentreId"`
	CostUnitID                string      `json:"costUnitId"`
	CreditAmount              float64     `json:"creditAmount"`
	CreditAmountCur           float64     `json:"creditAmountCur"`
	CurrencyID                string      `json:"currencyId"`
	CustomerID                string      `json:"customerId"`
	DebitAmount               float64     `json:"debitAmount"`
	DebitAmountCur            float64     `json:"debitAmountCur"`
	Description               string      `json:"description"`
	Document                  string      `json:"document"`
	FiscalYear                int         `json:"fiscalYear"`
	FixedAssetID              string      `json:"fixedAssetId"`
	JournalID                 string      `json:"journalId"`
	JournalTransaction        int         `json:"journalTransaction"`
	OpeningBalanceTransaction bool        `json:"openingBalanceTransaction"`
	PeriodNumber              int         `json:"periodNumber"`
	Quantity                  float64     `json:"quantity,omitempty"`
	SupplierID                string      `json:"supplierId"`
	TransactionDate           string      `json:"transactionDate"`
	VatAdjusted               bool        `json:"vatAdjusted"`
	VatAmount                 float64     `json:"vatAmount"`
	VatCodeID                 interface{} `json:"vatCodeId,omitempty"`
	VatType                   int         `json:"vatType,omitempty"`
}
