package poweroffice

type VATCodes []VATCode

type VATCode struct {
	// Gets the identifier. This identifier is unique and assigned by
	// PowerOffice Go when a new entity is saved, and should be provided when an
	// entity should be edited. If this identifier is not provided, PowerOffice
	// Go will try to create a new entity.
	ID int `json:"id"`
	// Gets or sets the code.
	Code string `json:"code"`
	// Gets or sets the name.
	Name string `json:"name"`
	// Gets or sets the description.
	Description string `json:"description"`
	// Gets or sets the rate. This is a value between 0 and 100. With 0
	// representing 0% VAT and 100 representing 100% VAT.
	Rate float64 `json:"rate"`
	// Gets or sets a value indicating whether this instance is active.
	IsActive bool `json:"isActive"`
	// Gets the date that this VAT code is active from.
	ValidFrom string `json:"validFrom"`
	// Gets or sets a value indicating whether this VAT code is custom created.
	IsCustom bool `json:"isCustom"`
	// Gets or sets the VAT basis ratio (Norwegian: Forholdsmessig fradrag MVA).
	// This is a value between 0 and 1. With 0 representing 0% VAT basis ratio
	// and 1 representing 100% VAT basis ratio. Example: 1000 kr with 50% VAT
	// basis ratio and 25% VAT rate is calculated: 1000 0.5 0.25 = 125 kr.
	VatBasisRatio float64 `json:"vatBasisRatio"`
	// Gets the date which the VAT code expires.
	Validto string `json:"validto,omitempty"`
}
type AutoGenerated struct {
	Data []struct {
	} `json:"data"`
	Success bool `json:"success"`
	Count   int  `json:"count"`
}
type Locations []Location

type Location struct {
	// Gets or sets the code of the location. This is an unique identificator.
	Code string `json:"Code"`
	// Gets the identifier. This identifier is unique and assigned by PowerOffice Go when a new entity is saved, and should be provided when an entity should be edited. If this identifier is not provided, PowerOffice Go will try to create a new entity.
	ID int `json:"Id"`
	// Gets or sets a value indicating whether this location is active. Defaults to true.
	IsActive bool `json:"IsActive"`
	// Gets or sets the name of the location.
	Name string `json:"Name"`
}

type ManualJournalVouchers []ManualJournalVoucher

type ManualJournalVoucher struct {
	// Gets the created date. This value is assigned by PowerOffice Go when the
	// voucher is posted.
	CreatedDate Date `json:"CreatedDate"`
	// Gets or sets the currency code.
	CurrencyCode string `json:"CurrencyCode"`
	// Gets or sets the code of the Department .
	DepartmentCode string `json:"DepartmentCode"`
	// Gets or sets the description.
	Description string `json:"Description"`
	// Gets or sets the code of the custom dimension 1.
	Dim1Code string `json:"Dim1Code"`
	// Gets or sets the code of the custom dimension 2.
	Dim2Code string `json:"Dim2Code"`
	// Gets or sets the code of the custom dimension 3.
	Dim3Code string `json:"Dim3Code"`
	// Gets or sets ExternalImportReference. Can be used to correlate/duplicate
	// check vouchers. Must be a unique value for a given client. Max length is
	// 50 characters.
	ExternalImportReference string `json:"ExternalImportReference"`
	// Set to true if the voucher has VoucherDocumentation imported through the
	// API.
	HasImportedDocumentation bool `json:"HasImportedDocumentation"`
	// Gets the identifier. This identifier is unique and assigned by
	// PowerOffice Go when a new entity is saved.
	ID string `json:"Id"`
	// Gets or sets the imported Voucher number. This value can be used to set a
	// reference from the external system creating the voucher.
	ImportedVoucherNo int `json:"ImportedVoucherNo"`
	// Gets information whether this voucher has been reversed. This can be done
	// by the API through the Reverse method in the voucher service.
	IsReversed bool `json:"IsReversed"`
	// Gets or sets the manual journal lines ManualJournalVoucherLine .
	Lines ManualJournalVoucherLines `json:"Lines"`
	// Gets or sets the code of the Project .
	ProjectCode string `json:"ProjectCode"`
	// Gets or sets the SAF-T batch id. This is the ID of the batch in the
	// system that transferred the voucher. Should be set if this voucher is a
	// batch voucher containing the entries of multiple vouchers in the external
	// system. When this voucher is exported to SAF-T, this property is
	// transactions BatchID in the SAF-T file. The external systems SAF-T export
	// should set the same BatchId on all the transactions that are included in
	// this Voucher to ensure audit trail. Max length is 35 characters.
	SaftBatchID string `json:"SaftBatchId"`
	// Gets or sets the SAF-T source id. This is the ID of the system that
	// generated the voucher. When this voucher is exported to SAF-T, this
	// property is mapped on the transactions SourceID in the SAF-T file. If the
	// creating system is required to export it's own SAF-T file, this source id
	// should correspond with the SystemID in the SAF-T file of the external
	// system to ensure an audit trail. Max length is 35 characters.
	SaftSourceID string `json:"SaftSourceId"`
	// Gets or sets the voucher date.
	VoucherDate Date `json:"VoucherDate"`
	// Gets the Voucher number. This value is assigned by PowerOffice Go when
	// the voucher is posted.
	VoucherNo int `json:"VoucherNo"`
}

type ManualJournalVoucherLines []ManualJournalVoucherLine

type ManualJournalVoucherLine struct {
	// Gets or sets the account code this voucher line should be posted on. The
	// account code can either be the code on a GeneralLedgerAccount , or if the
	// accounting entry is on a sub ledger account, the code provided can be for
	// a Customer , Supplier or Employee .
	AccountCode int `json:"AccountCode"`
	// Gets or sets the total amount of the line. This is the amount to be
	// posted in the same currency as the voucher, or the currency overridden on
	// the line for some voucher types. The amount is specified VAT inclusive.
	// Specifying a negative amount here will post the amount as credit and a
	// positive amount will post the amount as debit on all voucher types except
	// OutgoingInvoiceVoucher / OutgoingInvoiceVoucherLine .
	Amount float64 `json:"Amount"`
	// Gets or sets the customer identification (Norwegian: KID).
	CID string `json:"CID"`
	// Gets or sets the currency code.
	CurrencyCode string `json:"CurrencyCode"`
	// Gets or sets the normalized currency rate of the line (factor to multiply
	// amount in voucher currency with to get amount in local currency).
	CurrencyRate int `json:"CurrencyRate"`
	// Gets or sets the custom matching reference. Voucher lines with this value
	// can be matched with other entries with same CustomMatchingReference.
	CustomMatchingReference string `json:"CustomMatchingReference"`
	// Gets or sets the voucher line date. The accounting entry for this line will be posted on this date.
	Date Date `json:"Date"`
	// Gets or sets the code of the Department . If set to "-1", this line will
	// not inherit the department set on the voucher level, and no department
	// will be posted to Go for this line
	DepartmentCode string `json:"DepartmentCode"`
	// Gets or sets the description.
	Description string `json:"Description"`
	// Gets or sets the code of the custom dimension 1. If set to "-1", this
	// line will not inherit the value set on the voucher level, and no Dim1
	// will be posted to Go for this line
	Dim1Code string `json:"Dim1Code"`
	// Gets or sets the code of the custom dimension 2. If set to "-1", this
	// line will not inherit the value set on the voucher level, and no Dim2
	// will be posted to Go for this line
	Dim2Code string `json:"Dim2Code"`
	// Gets or sets the code of the custom dimension 3. If set to "-1", this
	// line will not inherit the value set on the voucher level, and no Dim3
	// will be posted to Go for this line
	Dim3Code string `json:"Dim3Code"`
	// Gets or sets the external import line reference. Used by external systems
	// to match voucher lines. Max length is 50 characters.
	ExternalImportLineReference string `json:"ExternalImportLineReference"`
	// Gets the identifier. This identifier is unique and assigned by
	// PowerOffice Go when a new entity is saved.
	ID int `json:"Id"`
	// Gets or sets the code of the Product .
	ProductCode string `json:"ProductCode"`
	// Gets or sets the code of the Project . If set to "-1", this line will not
	// inherit the project set on the voucher level, and no project will be
	// posted to Go for this line
	ProjectCode string `json:"ProjectCode"`
	// Gets or sets the quantity.
	Quantity int `json:"Quantity"`
	// Gets or sets the code of the VatCode for this voucher line. Vat will be
	// calculated depending on what code is provided from the total amount
	// inclusive (Amount). If not provided, the voucher will use default VAT
	// code 0 on the line, resulting in a vat free transaction.
	VatCode string `json:"VatCode"`
	// Gets or sets the VatReturnSpecification . Entries that are vat reportable
	// might report vat return specifications from 2022. If not provided, the
	// voucher will use the vat returns specification that is default on the
	// account if there is any, otherwise
	// GoApi.Common.VatReturnSpecification.None .
	VatReturnSpecification VatReturnSpecification `json:"VatReturnSpecification"`
}

type VatReturnSpecification struct {
}
